server:
  port: 8006

spring:
  application:
    name: provider-payment-service
  cloud:
    consul:
#      host: 192.168.0.102
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}