server:
  port: 80

spring:
  application:
    name: consumer-payment-client
  cloud:
    consul:
#      host: 192.168.0.102
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}