server:
  port: 9002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
#        server-addr: 192.168.0.102:8080 #换成nginx的1111端口，做集群

management:
  endpoints:
    web:
      exposure:
        include: '*'


