server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          skipSslValidation: true #跳过ssl认证
          uri: https://github.com/zhangrq1983/springcloud-config.git
          search-paths:
            - season2
      label: master

#rabbitmq:
#  host: localhost
#  port: 5672
#  username: guest
#  password: guest

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #入驻地址
  instance:
    hostname: config-center-3344

## 暴露bus刷新配置的端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "bus-refresh"
