server:
  port: 3344

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          skipSslValidation: true #跳过ssl认证
          uri: https://github.com/zhangrq1983/springcloud-config.git
          search-paths:
            - season2
      label: master
rabbitmq: #rabbitmq相关配置，15672是web管理端口，5672是mq访问端口
  host: localhost
  port: 5672
  username: guest
  password: guest

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #入驻地址
  instance:
    instance-id: config-center-3344
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 #eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到最后一次心跳后等待时间上限，单位秒 默认90秒，超时将剔除

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

#  curl -X POST "http://localhost:3344/actuator/bus-refresh"
#  curl -X POST "http://localhost:3344/actuator/bus-refresh/config-client:3355"
