server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://provider-payment-service
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://provider-payment-service
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
#            - After=2020-03-24T16:55:10.988+08:00[Asia/Shanghai]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Cookie=username,zzyy
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
#            - Host=**.atguigu.com
#            - Method=GET
#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
#             过滤
#          filters:
#          - AddRequestHeader=X-Request-red, blue
eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #入驻地址
  instance:
    hostname: cloud-gateway-9527
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1 #eureka客户端向服务端发送心跳的时间间隔 单位秒 默认30
    lease-expiration-duration-in-seconds: 2 #eureka服务端在收到最后一次心跳后等待时间上限，单位秒 默认90秒，超时将剔除

